### PR TITLE
QSO info added to NullDisplay

### PR DESCRIPTION
**Pull request by GuusvanDooren**

### CODE REVIEW

**Comment by g4klx** [comment]
Cound not networkInfoInitialized and passCounter be member variables of CNullModem? Secondly what does passCounter do? Other than that I'm happy with this pull request.

**Comment by GuusvanDooren** [comment]
Hi Jonathan,

Thank you for your response.

I have used the same structure as you implemented the QSO info in the OLED routine.

Make networkInfoInitialized and passCounter member of CNullModem was not logic for me
because they are curently meber of OLED. Since i do not use OLED because of the I2C errors
i went to NullDisplay to have the QSO info available.

Passcounter countes the number of times the QSO info is set to IDLE. This is a refresh of the
assigned IP address as done in OLED.cpp



Met vriendelijke groet / With kind regards,

Guus van Dooren
Dooren Electronic Solutions
Boomdijk 6c
4417BE Hansweert
Netherlands
+31 113383540
dvmega@auria.nl

**Comment by g4klx** [comment]
Hi Guus, I've been thinking about this. I think it would be better to have a new display type rather than modify the NullDisplay which is used elsewhere. How about a new display type of "Cast" and base it on the work you've done for NullDisplay? You could also remove the cast flag too. That way you'd have a display type that is all your own to modify with no ramifications for other people?

**Comment by GuusvanDooren** [comment]
Hi Jonathan,

Thanks for your reply.

That is a good idea, i will do a new pull request soon.




Met vriendelijke groet / With kind regards,

Guus van Dooren
Dooren Electronic Solutions
Boomdijk 6c
4417BE Hansweert
Netherlands
+31 113383540
dvmega@auria.nl

**Pull request closed without merging**
