### PR TITLE
Further work on daemon under Linux. 

### PR DESCRIPTION
**Pull request by hacknix**
I have made the daemon code drop to a standard user on start-up for security reasons. I've also improved the logging for daemon code and created README.daemon.

### CODE REVIEW

**Comment by g0wfv** [comment]
**UNTESTED ...**

But I suspect MMDVMHost will fail to work with the HD44780 or the Adafruit displays as supersuser permissions are required to use the wiringPi library functions that manipulate the GPIO pins.

If I get the chance, I will test

**Comment by hacknix** [comment]
Hi G0WFW.  I believe you can use standard unix permissions to allow GPIO access from non-root users. I used to run svxlink as a non-root user and I used a GPIO pin for PTT. I don't have a display to test with but I will look in to it.

**Comment by g0wfv** [comment]
Hi Simon,

Now tested; it fails to start when you have compiled with the HD44780 screen defined - even if you tell MMDVMHost not to use a screen

The GPIO pins can be used by a non-root user if you initialise with wiringPiSetupSys (void);  and export the GPIO with the gpio program (call to external program with system() ???)  However MMDVMHost uses wiringPiSetup (void); which requires root permissions.

It is possible, but pin numbering will change within MMDVMHost.

More info here - http://wiringpi.com/reference/setup/

Tony

**Comment by g0wfv** [comment]
Failed at the first hurdle I checked (software PWM - used for backlight control) ...

_You must initialise wiringPi with one of wiringPiSetup(),  wiringPiSetupGpio() or wiringPiSetupPhys() functions. wiringPiSetupSys() is not fast enough, so you must run your programs with sudo._

So PWM backlight control will break (or not work as advertised!)

**Comment by hacknix** [comment]
Hi Tony,

Ok, makes sense. 

Have you tried adding the mmdvm user to group "gpio"?

73 - Simon

On 5 May 2016 08:47:46 BST, g0wfv <notifications@github.com> wrote:
>Hi Simon,
>
>Now tested; it fails to start when you have compiled with the HD44780
>screen defined - even if you tell MMDVMHost not to use a screen
>
>The GPIO pins can be used by a non-root user if you initialise with
>wiringPiSetupSys (void);  and export the GPIO with the gpio program
>(call to external program with system() ???)  However MMDVMHost uses
>wiringPiSetup (void); which requires root permissions.
>
>It is possible, but pin numbering will change within MMDVMHost.
>
>More info here - http://wiringpi.com/reference/setup/
>
>Tony
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/g4klx/MMDVMHost/pull/45#issuecomment-217095525

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by g0wfv** [comment]
wiringPiSetupSys() isn't fast enough to run software PWM - the hardware PWM side should be fine (I think?!)

Perhaps a check could be added to your code to catch conflicting settings in the ini file (daemon AND HD44780/Adafruit)

I need to do some further testing - but on with the day .....

**Comment by hacknix** [comment]
Yes, I can look at adding a check, or alternatively, a boolean value in the config to turn the setuid() and setgid() operations off. I will look into this.

73 Simon

**Comment by hacknix** [comment]
I added code to do this as suggested, using:

#if !defined(HD44780)
...
#endif

**Comment by g0wfv** [comment]
Hah! that was going to be another suggestion!  You need to add Adafruit to that too.

**Comment by g0wfv** [comment]
In fact, no you don't because the Adafruit is already defined with HD44780!

**Comment by g0wfv** [comment]
OK, that works with HD44780 support compiled in, although I don't get the message in the log that it's disabled setuid when I run with Daemon=1 ...

::LogMessage("Warning: dropping root permissions in daemon mode is disabled with HD44780 display");

**Comment by g0wfv** [comment]
Apologies, yes I do!  I was just looking in the wrong place in the log (it's the first line in the log before the header lines!  Don;t know why I was expecting it further down, d'oh!)

**Comment by hacknix** [comment]
Thanks for testing Tony. :-)

**Comment by g0wfv** [comment]
Although this ...

W: 2016-05-05 09:36:59.362 Cannot open the DMR Id lookup file - DMRIds.dat

... crops up when running as daemon (with setuid disabled - don't know if it's the same for you without the HD44780)

Another suggestion for you - You start the dropping setuid message with the word "Warning", but use LogMessage() - would it not be more appropriate to use LogWarning() if that's what you intend?

**Comment by hacknix** [comment]
Yes, that's true. It's because the daemon code does a "cd /", so you need the full path to the file. I will put a note in the readme about that. 

You are correct about LogMessage() / LogWarning(). I will change that.

**Comment by g0wfv** [comment]
You're welcome :-)  Thanks for doing this - should help those of us using screen to daemonise it currently.

**Pull request merged**
