### PR TITLE
Update HD44780.cpp

### PR DESCRIPTION
**Pull request by Giorgiofox**
Different colors on different MMDVM status (mostly only on DMR mode at the moment) and better formatting for 16x2 displays

Need to be completed with all systems like Fusion and Dstar adding color row where activated. 

Hope you will like :)

### CODE REVIEW

**Comment by Giorgiofox** [comment]
Please merge  HD44780.H
is important! Without it there are compiling errors.


Thanks
73
Giorgio IZ2XBZ

2016-05-02 21:51 GMT+02:00 Jonathan Naylor <notifications@github.com>:

> Merged #36 <https://github.com/g4klx/MMDVMHost/pull/36>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/g4klx/MMDVMHost/pull/36#event-648037716>
>



-- 
Giorgio
giorgiofox@gmail.com
Secure: giorgiofox@protonmail.ch
Ham: iz2xbz@aribrescia.it

**Comment by g0wfv** [comment]
How well will this play with a vanilla HD44780?

**Comment by Giorgiofox** [comment]
This work only with adafruit display that have an i2c controller for
backlight RGB led.


2016-05-02 22:08 GMT+02:00 g0wfv <notifications@github.com>:

> How well will this play with a vanilla HD44780?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/g4klx/MMDVMHost/pull/36#issuecomment-216348024>
>



-- 
Giorgio
giorgiofox@gmail.com
Secure: giorgiofox@protonmail.ch
Ham: iz2xbz@aribrescia.it

**Comment by g0wfv** [comment]
I understand that, but the adafruit code and the HD44780 code are all in the same file. Just worrying something will introduce an incompatibility between the two LCDs at some stage.

**Comment by Giorgiofox** [comment]
OK, just pulled and update with #ifdef ADAFRUIT_DISPLAY on every color
change call function to avoid problem with non adafruit display
compiling with:
sudo make all --makefile Makefile.Pi.HD44780

give no problem ;)

2016-05-02 22:54 GMT+02:00 g0wfv <notifications@github.com>:

> I understand that, but the adafruit code and the HD44780 code are all in
> the same file. Just worrying something will introduce an incompatibility
> between the two LCDs at some stage.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/g4klx/MMDVMHost/pull/36#issuecomment-216360377>
>



-- 
Giorgio
giorgiofox@gmail.com
Secure: giorgiofox@protonmail.ch
Ham: iz2xbz@aribrescia.it

**Pull request merged**
