### PR TITLE
Auto maintenance of DMR ID file from crontab

### PR DESCRIPTION
**Pull request by g0wfv**

### CODE REVIEW

**Comment by cyanide-burnout** [comment]
Why it is not from primary source of BrandMeister?
http://registry.dstar.su/dmr/DMRIds.php

**Comment by g0wfv** [comment]
Because that file is pre-generated and at the current time hasn't been
updated in 5 days (09:26 5/5/16)

The DMR-MARC page at
http://www.dmr-marc.net/cgi-bin/trbo-database/datadump.cgi allows access to
the live database at the time of file generation.

The network you connect to is irrelevant, the same IDs are used on all
three DMR networks.

On Fri, Jun 10, 2016 at 6:05 PM Artem Prilutskiy <notifications@github.com>
wrote:

> Why it is not from primary source of BrandMeister?
> http://registry.dstar.su/dmr/DMRIds.php
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/pull/89#issuecomment-225239277>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AQf_4lNH3VJh49ozOS5WAnqTHusa8onKks5qKZlCgaJpZM4Iy5Zc>
> .
>
-- 

A J Corbett

G0WFV

**Comment by g0wfv** [comment]
Or maybe it isn't - I can't see the PHP to see whether the file is
generating a live ID list or pulling a pre-made file - however there are
some other interesting files in the same directory as that file that may be
useful to me!

On Sat, Jun 11, 2016 at 8:09 AM Tony Corbett <tonyc.uk@gmail.com> wrote:

> Because that file is pre-generated and at the current time hasn't been
> updated in 5 days (09:26 5/5/16)
>
> The DMR-MARC page at
> http://www.dmr-marc.net/cgi-bin/trbo-database/datadump.cgi allows access
> to the live database at the time of file generation.
>
> The network you connect to is irrelevant, the same IDs are used on all
> three DMR networks.
>
> On Fri, Jun 10, 2016 at 6:05 PM Artem Prilutskiy <notifications@github.com>
> wrote:
>
>> Why it is not from primary source of BrandMeister?
>> http://registry.dstar.su/dmr/DMRIds.php
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/g4klx/MMDVMHost/pull/89#issuecomment-225239277>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/AQf_4lNH3VJh49ozOS5WAnqTHusa8onKks5qKZlCgaJpZM4Iy5Zc>
>> .
>>
> --
>
> A J Corbett
>
> G0WFV
>
-- 

A J Corbett

G0WFV

**Comment by cyanide-burnout** [comment]
It generates actual list each time you call it

**Comment by g0wfv** [comment]
So I see now!  The benefit of the other list is that it can pull other info
also if needed at a later date.  For all we know, it is pulling from the
same source anyway.

On Sat, Jun 11, 2016 at 8:40 AM Artem Prilutskiy <notifications@github.com>
wrote:

> It generates actual list each time you call it
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/pull/89#issuecomment-225342635>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AQf_4s1JC-_zlacJgXGFp5Fnd9mMGDVvks5qKmZ9gaJpZM4Iy5Zc>
> .
>
-- 

A J Corbett

G0WFV

**Comment by cyanide-burnout** [comment]
This list has some deviations from MARC database but actually it is the same for 100% as on all BM servers.

**Comment by g0wfv** [comment]
Which is the more authoritative source?

On Sat, Jun 11, 2016 at 10:12 AM Artem Prilutskiy <notifications@github.com>
wrote:

> This list has some deviations from MARC database but actually it is the
> same for 100% as on all BM servers.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/pull/89#issuecomment-225346271>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AQf_4rvATjvNFjm0mm1B_ZAljxFvi56Uks5qKnvugaJpZM4Iy5Zc>
> .
>
-- 

A J Corbett

G0WFV

**Comment by cyanide-burnout** [comment]
> Which is the more authoritative source?

Yes, it is true for BrandMeister network

**Pull request merged**
