### PR TITLE
FMControl.cpp and FMNetwork.cpp changes  needed for FMGateway to Asterisk USRP

### PR DESCRIPTION
**Pull request by ve2dje**
Changes to  FMControl.cpp and FMNetwork.cpp needed to match audio format from  MMDVMHost Fm mode and 
USRP driver for Asterisk ( ASL) . Needed for FMGateway.py 
Changes  to FMControl.cpp to switch   size  chunks from  168 to 160
Changes to FMNetwork.cpp to :
Change audio format from  U16BE to S16LE
Disable FM packet from invalid source check , not working properly  with USRP Asterisk

### CODE REVIEW

**Review by randybuildsthings — COMMENTED** [review]
Quite the omnibus PR here. Way more than what's described in the PR title. M17, AX25, and FM aspects all bundled together. Is there a reason (other than doing it all at once) that this is all one PR?

**Comment by g4klx** [comment]
I think the pull request is against an old version of the source tree. I hope he’ll do a pull to bring the main code up to date. As it stands I can’t apply it without lots of damage to the code.


Sent from Yahoo Mail for iPhone


On Friday, March 5, 2021, 16:19, Randy Hall <notifications@github.com> wrote:




@randybuildsthings commented on this pull request.

Quite the omnibus PR here. Way more than what's described in the PR title. M17, AX25, and FM aspects all bundled together. Is there a reason (other than doing it all at once) that this is all one PR?

**Comment by ve2dje** [comment]
Thanks for the comment, My first  PR ,  I did not know I could pull only
the 2 files  I  have to edit.
Read the wiki but I did not  hook on that  .

Anything I could  do to correct ??

Richard


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ve2dje** [comment]
I made shure I  made the pull from the latest version , the latest file
change was for MMDVM.ini dated 14  days ago.
It's the same  version I pulled.
i  could  try  to issue a new  pull only the 2 files I  modified ????

What do you suggest.

Sorry  for the  problem. Steep learning curve

Richard

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by g4klx** [comment]
I think this pull request is against the master branch and not the M17_AX25_FM one, hence the massive changes shown. I cannot apply this PR as-is. I think the solution to this is probably best done in the MMDVM firmware by making the block length slightly smaller, and only change the format in the host, maybe with an option to choose the format.

**Comment by g4klx** [comment]
I've manually applied your changes and so I'll close this pull request.

**Pull request closed without merging**
