### PR TITLE
NetBSD support

### PR DESCRIPTION
**Pull request by jg1uaa**
different from other systems:
- the value for usleep() should be less than 1,000,000
- struct timeval tv_usec is 32bit (not 64bit)
so need treatment for them.

### CODE REVIEW

**Comment by g4klx** [comment]
Is there a #define for NetBSD I can use to control compilation of the sleep changes?

**Comment by jg1uaa** [comment]
I think no need to make #if defined(__NetBSD__) ~ #endif section. These modified codes are also tested on Linux, OpenBSD and FreeBSD and no problem.
Of course I can separate NetBSD/other PC-UNIXes, but it increases test case.

**Comment by g4klx** [comment]
My concern is efficiency. Divides are expensive and not needed on the Linux platform. I don’t want to encumber Linux with slow code which isn’t needed.


Sent from Yahoo Mail for iPhone


On Tuesday, September 29, 2020, 12:57, SASANO Takayoshi <notifications@github.com> wrote:




I think no need to make #if defined(NetBSD) ~ #endif section. These modified codes are also tested on Linux, OpenBSD and FreeBSD and no problem.
Of course I can separate NetBSD/other PC-UNIXes, but it increases test case.

**Comment by g4klx** [comment]
I think the whole sleep/usleep should be replaced with nanosleep as that is the Posix standard, usleep is deprecated. Can you check that NetBSD also supports nanosleep?

The %03lu is correct as it is a long integer, for 64-bits it would be %03llu.

**Comment by jg1uaa** [comment]
NetBSD has nansosleep() so I replaced from sleep()/usleep().

And NetBSD's struct timeval.tv_usec is int(32bit), neither long(32/64bit) nor long long(64bit). I have no idea to avoid using cast.
(sometimes compiler says warning about 64bit-value format string, I think using PRId64 definition from <inttypes.h> instead of %lld directly.)

**Comment by krytarowski** [comment]
> My concern is efficiency. Divides are expensive and not needed on the Linux platform. I don’t want to encumber Linux with slow code which isn’t needed.

1. Linux kernel still performs the same division inside the kernel so no gain in running it in the kernel space....
2. NetBSD is stricter with the standard here.

**Comment by shawnchain** [comment]
Now the code of MMDVMHost gets more and more advavnced  that requires C++11 to compile. 
And I guess the CPU/System with C++11 runtime should be powerful enough to run the divide.
But I don't like that, and I think the Host code should keep as simple as possible so that we could run it even on embedded device...

**Comment by krytarowski** [comment]
This divide is executed during a sleep function. Every sleep call should take magnitudes of time more than a single division operation.

**Comment by g4klx** [comment]
I've manually added these updates to all of the IPv4 and IPv6 versions of the MMDVM suite of programs. So I'm closing the pull request, but your changes are now included.

**Pull request closed without merging**
