### PR TITLE
Use a dot as date separator optionally

### PR DESCRIPTION
**Pull request by phl0**
I added a simple config option to change the field seaparator for displaying the date on Nextion and HD44780 displays. If desired I would implement another option to change it to MDY format.

### CODE REVIEW

**Comment by g4klx** [comment]
Great work. I've merged it as you can see. Could you add the USA version too, and don't forget to update the TFTSerial display also.

**Comment by phl0** [comment]
Will do.

**Comment by phl0** [comment]
[x] done. See #104.

**Comment by g0wfv** [comment]
Florian,

Hah!  One of the things I had on my todo list!

Mind if I have a go at changing this to link to a locale specified in
MMDVM.ini, eg en_US, en_GB, de_DE etc?  I think it may be more flexible
this way.  Not sure if this will have a knock on effect to Jon's code for
the logging though (planning on using std::setlocale and rejigging how it
prints the date)

Tony

On Wed, Jun 22, 2016 at 1:16 PM Florian (DF2ET) <notifications@github.com>
wrote:

> [x] done. See #104 <https://github.com/g4klx/MMDVMHost/pull/104>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/pull/103#issuecomment-227725373>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AQf_4rbuNWQvRVG3P9FL5lC7l1L7fVyvks5qOSexgaJpZM4I7pGD>
> .
>
-- 

A J Corbett

G0WFV

**Comment by g0wfv** [comment]
In fact, I think I can get it to print according to the system locale
.......

On Wed, Jun 22, 2016 at 7:23 PM Tony Corbett <tonyc.uk@gmail.com> wrote:

> Florian,
>
> Hah!  One of the things I had on my todo list!
>
> Mind if I have a go at changing this to link to a locale specified in
> MMDVM.ini, eg en_US, en_GB, de_DE etc?  I think it may be more flexible
> this way.  Not sure if this will have a knock on effect to Jon's code for
> the logging though (planning on using std::setlocale and rejigging how it
> prints the date)
>
> Tony
>
> On Wed, Jun 22, 2016 at 1:16 PM Florian (DF2ET) <notifications@github.com>
> wrote:
>
>> [x] done. See #104 <https://github.com/g4klx/MMDVMHost/pull/104>.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/g4klx/MMDVMHost/pull/103#issuecomment-227725373>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/AQf_4rbuNWQvRVG3P9FL5lC7l1L7fVyvks5qOSexgaJpZM4I7pGD>
>> .
>>
> --
>
> A J Corbett
>
> G0WFV
>
-- 

A J Corbett

G0WFV

**Comment by g0wfv** [comment]
Yes I can!  I wrote a small test program which pulls the system locale
(en_GB.UTF-8 in my case) and prints the date/time.  It then changes the
locale within the program to de_DE.UTF8 and using the same code, prints the
date/time, then repeats for en_US.UTF8.  The output is below ...

*System locale is: en_GB.UTF-8*
*Date is: 22/06/16*
*Time is: 20:00:18*

*Changing locale to de_DE ...*

*Program locale is: de_DE.UTF8*
*Date is: 22.06.2016*
*Time is: 20:00:18*

*Changing locale to en_US ...*

*Program locale is: en_US.UTF8*
*Date is: 06/22/2016*
*Time is: 08:00:18 PM*

Looking at those outputs, it's obvious that the time won't fit on all
screens (I'm thinking 16x2 HD44780 here!) others should be fine, and I
assume the Nextion would cope also?  I'm planning on leaving the time
format hard coded on 2x16, but everything else can go via a locale setting.

Therefore, our options are as follows ...

1.  Pull the system locale and print the date/time accordingly.
2.  Set the locale internally in MMDVMHost (via MMDVM.ini) and print the
date/time accordingly.

My preference is option 1 as it requires no code changes whereas option 2
requires a slight code change and is open to being messed up by a
configuration error in MMDVM.ini

Doing date and time formats this way, we're not tied to whatever formats we
hard code in if statements.

Comments?


On Wed, Jun 22, 2016 at 7:30 PM Tony Corbett <tonyc.uk@gmail.com> wrote:

> In fact, I think I can get it to print according to the system locale
> .......
>
> On Wed, Jun 22, 2016 at 7:23 PM Tony Corbett <tonyc.uk@gmail.com> wrote:
>
>> Florian,
>>
>> Hah!  One of the things I had on my todo list!
>>
>> Mind if I have a go at changing this to link to a locale specified in
>> MMDVM.ini, eg en_US, en_GB, de_DE etc?  I think it may be more flexible
>> this way.  Not sure if this will have a knock on effect to Jon's code for
>> the logging though (planning on using std::setlocale and rejigging how it
>> prints the date)
>>
>> Tony
>>
>> On Wed, Jun 22, 2016 at 1:16 PM Florian (DF2ET) <notifications@github.com>
>> wrote:
>>
>>> [x] done. See #104 <https://github.com/g4klx/MMDVMHost/pull/104>.
>>>
>>> —
>>> You are receiving this because you are subscribed to this thread.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/g4klx/MMDVMHost/pull/103#issuecomment-227725373>,
>>> or mute the thread
>>> <https://github.com/notifications/unsubscribe/AQf_4rbuNWQvRVG3P9FL5lC7l1L7fVyvks5qOSexgaJpZM4I7pGD>
>>> .
>>>
>> --
>>
>> A J Corbett
>>
>> G0WFV
>>
> --
>
> A J Corbett
>
> G0WFV
>
-- 

A J Corbett

G0WFV

**Comment by phl0** [comment]
Tony,

sorry I was away from the computer for a while. Had a Twitter QSO with PD0ZRY. He was admitting that it is limited to English and American formats. I thought that settings something like "DateFormat=D.M.Y" would be a good solution. But yours is even better. Deriving the date format from the locale saves separate entries in the config file. And as you have coded it already I would say: Go for it ;-)

   vy73 de Florian DF2ET

**Comment by g0wfv** [comment]
I haven't quite coded it yet - I've done the HD44780 code, just getting my
head around the Nextion code having never looked at it before (seems simple
enough at first glance!!)

I've tested with GB and US formats on the Pi with a 2x16 LCD but that's as
far as I can go (DE and possibly other locales are the same when displayed
on my LCD so will have to wait for others using other LCDs to report in
with problems if I've introduced any!)

I'll let you know when I've done it in my develop repo and you can have a
quick test of the Nextion code before I submit a pull request to Jon (if
you don't mind that is!) I'm actually surprised how simple the locale
change is!

One question, t2.txt I am assuming is in the HMI for the Nextion - how long
is it???  will it cope with a couple of extra characters over what is being
output at the moment?  you may need to tweek that one a bit for me as I
*REALLY* don't know what I'm doing with that one.  The DE locale outputs
date as DD.MM.YYYY (2 extra characters) and the US locale outputs time in
12 hour format as HH:MM:SS XX (where XX is AM or PM - 2 extra characters!)

On Wed, Jun 22, 2016 at 9:00 PM Florian (DF2ET) <notifications@github.com>
wrote:

> Tony,
>
> sorry I was away from the computer for a while. Had a Twitter QSO with
> PD0ZRY. He was admitting that it is limited to English and American
> formats. I thought that settings something like "DateFormat=D.M.Y" would be
> a good solution. But yours is even better. Deriving the date format from
> the locale saves separate entries in the config file. And as you have coded
> it already I would say: Go for it ;-)
>
> vy73 de Florian DF2ET
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/pull/103#issuecomment-227859318>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AQf_4rtc0BycZUqVkYZ0-Jpz94bD40C0ks5qOZRcgaJpZM4I7pGD>
> .
>
-- 

A J Corbett

G0WFV

**Comment by phl0** [comment]
Tony,

no problem. I can test your code with a 3.5" Nextion and HD44780 as 20x4 (which can be configured as 16x2 for testing purposes).

t2 is actually a text layer defined in the Nextion layout. I currently do not have the sources for it at hand. Will have a look at these tomorrow and let you know how many chars fit into t2. It can be extended of course. I can change the binary screen layouts for the Nextions if necessary.

   vy73 de Florian DF2ET

**Comment by g0wfv** [comment]
OK have a look at the code in
https://github.com/g0wfv/MMDVMHost/tree/develop ... by the sounds of it the
t2.txt should work as-is (fingers crossed!)

I would be grateful if you could test the HD44780 sizes that your able to
also (I must get me a 20x4!)

On Wed, Jun 22, 2016 at 9:42 PM Florian (DF2ET) <notifications@github.com>
wrote:

> Tony,
>
> no problem. I can test your code with a 3.5" Nextion and HD44780 as 20x4
> (which can be configured as 16x2 for testing purposes).
>
> t2 is actually a text layer defined in the Nextion layout. I currently do
> not have the sources for it at hand. Will have a look at these tomorrow and
> let you know how many chars fit into t2. It can be extended of course. I
> can change the binary screen layouts for the Nextions if necessary.
>
> vy73 de Florian DF2ET
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/pull/103#issuecomment-227870126>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AQf_4mJKwtBb9v7n_R2RHEppTkKOFG-Uks5qOZ4lgaJpZM4I7pGD>
> .
>
-- 

A J Corbett

G0WFV

**Comment by g0wfv** [comment]
Incidentally, I think I'm 1 character out in formatting the time on larger
screen (which I don't have!) for 8 character time formats (GB / DE for
example!)  US should centre OK!  I'll apply the fix now, let me know if it
displays in the correct place!

On Wed, Jun 22, 2016 at 10:05 PM Tony Corbett <tonyc.uk@gmail.com> wrote:

> OK have a look at the code in
> https://github.com/g0wfv/MMDVMHost/tree/develop ... by the sounds of it
> the t2.txt should work as-is (fingers crossed!)
>
> I would be grateful if you could test the HD44780 sizes that your able to
> also (I must get me a 20x4!)
>
> On Wed, Jun 22, 2016 at 9:42 PM Florian (DF2ET) <notifications@github.com>
> wrote:
>
>> Tony,
>>
>> no problem. I can test your code with a 3.5" Nextion and HD44780 as 20x4
>> (which can be configured as 16x2 for testing purposes).
>>
>> t2 is actually a text layer defined in the Nextion layout. I currently do
>> not have the sources for it at hand. Will have a look at these tomorrow and
>> let you know how many chars fit into t2. It can be extended of course. I
>> can change the binary screen layouts for the Nextions if necessary.
>>
>> vy73 de Florian DF2ET
>>
>> —
>> You are receiving this because you commented.
>>
>>
>> Reply to this email directly, view it on GitHub
>> <https://github.com/g4klx/MMDVMHost/pull/103#issuecomment-227870126>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/AQf_4mJKwtBb9v7n_R2RHEppTkKOFG-Uks5qOZ4lgaJpZM4I7pGD>
>> .
>>
> --
>
> A J Corbett
>
> G0WFV
>
-- 

A J Corbett

G0WFV

**Comment by g0wfv** [comment]
PS, in en_US and other locales where the time format is greater than 10
characters, the format has been limited to 10 chars by design on the
HD44780 to avoid a half value being generated and possibly breaking things!

It will print HH:MM:SS X where X is an A or a P to denote AM or PM.

On Wed, Jun 22, 2016 at 10:23 PM Tony Corbett <tonyc.uk@gmail.com> wrote:

> Incidentally, I think I'm 1 character out in formatting the time on larger
> screen (which I don't have!) for 8 character time formats (GB / DE for
> example!)  US should centre OK!  I'll apply the fix now, let me know if it
> displays in the correct place!
>
> On Wed, Jun 22, 2016 at 10:05 PM Tony Corbett <tonyc.uk@gmail.com> wrote:
>
>> OK have a look at the code in
>> https://github.com/g0wfv/MMDVMHost/tree/develop ... by the sounds of it
>> the t2.txt should work as-is (fingers crossed!)
>>
>> I would be grateful if you could test the HD44780 sizes that your able to
>> also (I must get me a 20x4!)
>>
>> On Wed, Jun 22, 2016 at 9:42 PM Florian (DF2ET) <notifications@github.com>
>> wrote:
>>
>>> Tony,
>>>
>>> no problem. I can test your code with a 3.5" Nextion and HD44780 as 20x4
>>> (which can be configured as 16x2 for testing purposes).
>>>
>>> t2 is actually a text layer defined in the Nextion layout. I currently
>>> do not have the sources for it at hand. Will have a look at these tomorrow
>>> and let you know how many chars fit into t2. It can be extended of course.
>>> I can change the binary screen layouts for the Nextions if necessary.
>>>
>>> vy73 de Florian DF2ET
>>>
>>> —
>>> You are receiving this because you commented.
>>>
>>>
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/g4klx/MMDVMHost/pull/103#issuecomment-227870126>,
>>> or mute the thread
>>> <https://github.com/notifications/unsubscribe/AQf_4mJKwtBb9v7n_R2RHEppTkKOFG-Uks5qOZ4lgaJpZM4I7pGD>
>>> .
>>>
>> --
>>
>> A J Corbett
>>
>> G0WFV
>>
> --
>
> A J Corbett
>
> G0WFV
>
-- 

A J Corbett

G0WFV

**Comment by phl0** [comment]
Tony,

this is the en_GB version.

img_20160624_122553

bildschirmfoto vom 2016-06-24 12 27 31

**Comment by phl0** [comment]
de_DE.UTF-8

img_20160624_124358

bildschirmfoto vom 2016-06-24 12 45 15

**Comment by phl0** [comment]
And en_US with slightly changed .tft file for the Nextion displays. Have them in PR https://github.com/g0wfv/MMDVMHost/pull/1

img_20160624_130850_1

bildschirmfoto vom 2016-06-24 13 10 20

**Pull request merged**
