### PR TITLE
Fix ADC overflow message

### PR DESCRIPTION
**Pull request by juribeparada**

### CODE REVIEW

**Comment by juribeparada** [comment]
Hi phl0, according to SerialPort.cpp, the next "free" bit is the b6 (0x40). The b4 is in use by hasLockout(). Now we have free b7 only.

**Comment by phl0** [comment]
@juribeparada Sorry. My fault. You are correct. I definitely need to improve my C knowledge :-)

**Comment by juribeparada** [comment]
;-)

**Comment by phl0** [comment]
May put that line a little bit further down then so that the order of bits is better readable?

**Comment by juribeparada** [comment]
OK

**Comment by juribeparada** [comment]
Yes, but have to see my pull request in MMDVM/SerialPort.cpp also.

**Comment by iw9grl** [comment]
Hi dear the issue seems to be solved, but in Dstar there are many overflow......

**Comment by juribeparada** [comment]
Hi iw9grl, I can't test Dstar because I don't have any Dstar radio. Can you print the log?

**Pull request merged**
