### PR TITLE
IPv6: catch up current source

### PR DESCRIPTION
**Pull request by jg1uaa**
for a while I didn't maintained IPv6 source code, but today I updated.

### CODE REVIEW

**Comment by stefansaraev** [comment]
o/

any plans to merge ipv6 branch into master?

**Comment by g4klx** [comment]
At some stage, but the MMDVM Host is probably the least important program since almost all of its connections are local to the machine and are usually the loopback address. It is the gateways that need to be updated.
Jonathan  G4KLX

    On Monday, 31 August 2020, 19:13:52 BST, Stefan Saraev <notifications@github.com> wrote:  
 
 


o/

any plans to merge ipv6 branch into master?

**Comment by stefansaraev** [comment]
many people (including me) dont need gateways and use mmdvmhost to connect directly to masters. so merging this would be nice. it works

**Comment by g4klx** [comment]
That’s good to know.
I’ll look into it. I want all of the gateways to upgrade at more or less the same time.


Sent from Yahoo Mail for iPhone


On Wednesday, September 2, 2020, 19:51, Stefan Saraev <notifications@github.com> wrote:




many people (including me) dont need gateways and use mmdvmhost to connect directly to masters. so merging this would be nice. it works

**Comment by zarya** [comment]
> At some stage, but the MMDVM Host is probably the least important program since almost all of its connections are local to the machine and are usually the loopback address. It is the gateways that need to be updated. 

Sad since over 60% (5000+) of all mmdvm connections on BM are not from dmrgateway but mmdvmhost directly.

**Comment by g4klx** [comment]
You cannot be certain of that. DMR Gateways have only been identifying for about a year.


Sent from Yahoo Mail for iPhone


On Wednesday, September 2, 2020, 20:24, Rudy <notifications@github.com> wrote:





At some stage, but the MMDVM Host is probably the least important program since almost all of its connections are local to the machine and are usually the loopback address. It is the gateways that need to be updated.


Sad since over 60% (5000+) of all mmdvm connections on BM are not from dmrgateway but mmdvmhost directly.

**Comment by zarya** [comment]
If i can not see it how can you??

**Comment by jg1uaa** [comment]
Well, the heart of IPv6 support code is UDPSocket.cpp and UDPSocket.h.
I think they are good enough to fix and it's time to replace them in other clients such as YSF, P25, NXDN and FM.
DMRGateway and DAPNETGateway is already supported because I have these rigs and I can test them easily,
but I don't have YSF/P25/NXDN/FM/D-STAR systems on the other hand.

I can simply rewrite the code with IPv6-capable UDP code, I hope someone will test rewrited client.
Please take a while.

**Comment by g4klx** [comment]
Hi Sasano
I've done a lot of work on adding IPv6 to the gateways and other programs over the last few weeks. I have done some changes to UDPSocket but nothing too major. In most cases my work is in the IPv6 branch of the various programs, except for DMRGateway and MMDVMHost where they are on the SimpleDMR branch because of other changes that are being made.
Could you do pull requests on all of them please and work from there. I see that your pull request for the MMDVM Host includes a lot of extra changes made by me and other people and so I think you didn't get the latest version of my code before you did the pull request. A lot of the code is changing rapidly so you must do a pull from the repository before you make your pull request to ensure that there are no conflicts.
Jonathan  G4KLX

    On Friday, 4 September 2020, 21:51:50 BST, SASANO Takayoshi <notifications@github.com> wrote:  
 
 


Well, the heart of IPv6 support code is UDPSocket.cpp and UDPSocket.h.
I think they are good enough to fix and it's time to replace them in other clients such as YSF, P25, NXDN and FM.
DMRGateway and DAPNETGateway is already supported because I have these rigs and I can test them easily,
but I don't have YSF/P25/NXDN/FM/D-STAR systems on the other hand.

I can simply rewrite the code with IPv6-capable UDP code, I hope someone will test rewrited client.
Please take a while.

**Pull request merged**
