### PR TITLE
Initial LCDproc support

### PR DESCRIPTION
**Pull request by g0wfv**
Enables support of all displays that LCDd supports. (http://lcdproc.org/hardware.php3)

Enables the ability to remotely mount a display.

Takes the scrolling processing on LCD screens away from the host.

Uses a non-blocking TCP socket with a timeout configurable in the code (currently set to 2.5ms) - if no data is to be Tx'd to Rx'd in that time, the socket moves on until the next time round the loop.  The host was quite happy with a higher timeout value of 10ms and when you get towards 100ms it was noticeably affecting the audio processing.  I settled on 2.5ms as a low enough value where the host and the socket were happy.

Tested on DMR and D-Star (requires testing on YSF and P25 - code for these modes written blind!)

### CODE REVIEW

**Comment by g4klx** [comment]
You can set a select timeout to zero which may help. Also a writeable fed in select means that it is possible to write data without blocking. It also indicates a socket is connected when using non-blocking connects.

**Comment by g4klx** [comment]
fed = fd.

**Comment by g0wfv** [comment]
You reminded me of something I was going to look at - but forgot as I was
preoccupied with the screen layouts!

It works as is, however you are right, the only writeable fd int he select
is the STDIN debugger - I need to look at making the socketPrintf write to
a fd rather than send directly to the socket!  Currently, the write can
block (but hasn't yet for what it's worth!) D'oh!

To be continued .........

I'm also worried I've introduced a bug with the DMR ID lookup code as it's
no longer able to open the DMRIds.dat file ....

*M: 2016-10-28 13:37:52.226 DMR, Opening DMR Network*
*I: 2016-10-28 13:37:52.226 DMR Id Lookups*
*I: 2016-10-28 13:37:52.226     File: None*
*W: 2016-10-28 13:37:52.226 Cannot open the Id lookup file - *

I've identified something in my additions to Conf.cpp that doesn't make
sense ...


*else if (::strncmp(buffer, "[LCDproc]", 6U) == 0)*

The above works as does 7U (and I suspect 8U will also), but should be 9U
(as everything else is the length of the entire string) which
doesn't?!?!?!?!?!?

Otherwise, I haven't directly touched the DMR ID lookup code as far as I
can see ....

Puzzled ......

Tony 5B/G0WFV ;-)

-- 

A J Corbett

G0WFV

**Comment by g0wfv** [comment]
Nope, the DMRIds problem's not my code!  (recompiled with latest source in
master branch)

On Fri, Oct 28, 2016 at 4:41 PM Tony Corbett <tonyc.uk@gmail.com> wrote:

> You reminded me of something I was going to look at - but forgot as I was
> preoccupied with the screen layouts!
>
> It works as is, however you are right, the only writeable fd int he select
> is the STDIN debugger - I need to look at making the socketPrintf write to
> a fd rather than send directly to the socket!  Currently, the write can
> block (but hasn't yet for what it's worth!) D'oh!
>
> To be continued .........
>
> I'm also worried I've introduced a bug with the DMR ID lookup code as it's
> no longer able to open the DMRIds.dat file ....
>
> *M: 2016-10-28 13:37:52.226 DMR, Opening DMR Network*
> *I: 2016-10-28 13:37:52.226 DMR Id Lookups*
> *I: 2016-10-28 13:37:52.226     File: None*
> *W: 2016-10-28 13:37:52.226 Cannot open the Id lookup file - *
>
> I've identified something in my additions to Conf.cpp that doesn't make
> sense ...
>
>
> *else if (::strncmp(buffer, "[LCDproc]", 6U) == 0)*
>
> The above works as does 7U (and I suspect 8U will also), but should be 9U
> (as everything else is the length of the entire string) which
> doesn't?!?!?!?!?!?
>
> Otherwise, I haven't directly touched the DMR ID lookup code as far as I
> can see ....
>
> Puzzled ......
>
> Tony 5B/G0WFV ;-)
>
> --
>
> A J Corbett
>
> G0WFV
>
-- 

A J Corbett

G0WFV

**Comment by g0wfv** [comment]
Panic over - I should really try using an up-to-date MMDVM.ini template!

On Fri, Oct 28, 2016 at 5:07 PM Tony Corbett <tonyc.uk@gmail.com> wrote:

> Nope, the DMRIds problem's not my code!  (recompiled with latest source in
> master branch)
>
> On Fri, Oct 28, 2016 at 4:41 PM Tony Corbett <tonyc.uk@gmail.com> wrote:
>
> You reminded me of something I was going to look at - but forgot as I was
> preoccupied with the screen layouts!
>
> It works as is, however you are right, the only writeable fd int he select
> is the STDIN debugger - I need to look at making the socketPrintf write to
> a fd rather than send directly to the socket!  Currently, the write can
> block (but hasn't yet for what it's worth!) D'oh!
>
> To be continued .........
>
> I'm also worried I've introduced a bug with the DMR ID lookup code as it's
> no longer able to open the DMRIds.dat file ....
>
> *M: 2016-10-28 13:37:52.226 DMR, Opening DMR Network*
> *I: 2016-10-28 13:37:52.226 DMR Id Lookups*
> *I: 2016-10-28 13:37:52.226     File: None*
> *W: 2016-10-28 13:37:52.226 Cannot open the Id lookup file - *
>
> I've identified something in my additions to Conf.cpp that doesn't make
> sense ...
>
>
> *else if (::strncmp(buffer, "[LCDproc]", 6U) == 0)*
>
> The above works as does 7U (and I suspect 8U will also), but should be 9U
> (as everything else is the length of the entire string) which
> doesn't?!?!?!?!?!?
>
> Otherwise, I haven't directly touched the DMR ID lookup code as far as I
> can see ....
>
> Puzzled ......
>
> Tony 5B/G0WFV ;-)
>
> --
>
> A J Corbett
>
> G0WFV
>
> --
>
> A J Corbett
>
> G0WFV
>
-- 

A J Corbett

G0WFV

**Comment by g0wfv** [comment]
As an initial stab, it's now ready to go, I think .....

**Comment by phl0** [comment]
Ok, some info from Tony and my debug session tonight:

If you would like to use the same wiring for a HD44780 display as it was used when the display was directly driven by MMDVMHost then use the following in /etc/LCDd.conf:

```
[hd44780]
ConnectionType=raspberrypi
#ConnectionType=rpi
Backlight=no
Size=16x2
pin_D4=17
pin_D5=18
pin_D6=27
pin_D7=22
pin_EN=8
pin_RS=7
```

The hd44780.so driver seems to be outdated on my Raspbian packages. That resulted in the error:

```
Oct 29 21:59:10 mmdvm LCDd: check_board_rev: This board is not recognized as a Raspberry Pi!
Oct 29 21:59:10 mmdvm LCDd: Driver [hd44780] init failed, return code -1
Oct 29 21:59:10 mmdvm LCDd: Could not load driver hd44780
Oct 29 21:59:10 mmdvm LCDd: There is no output driver
Oct 29 21:59:10 mmdvm LCDd: Critical error while initializing, abort.
```

being shown in the syslog. Solution is to use an updated hd44780.so that I got from here:

http://www.forum-raspberrypi.de/Thread-libreelec-5-0-5-rpi2-lcd-hd44780-probleme

Direct download: https://www.dropbox.com/s/mtkv226gi83ktra/hd44780.so

And one bug that affects the P25 display: On every first P25 transmission the 4th character of the callsign is missing. All subsequent transmissions are ok. The bug is obviously caused by LCDd. I tcpdumped what is beeing written to LCDd and in there the callsign is definitely correct. The error looks like:

_t6c_zfc

**Comment by g0wfv** [comment]
Thanks @phl0 - Good debug session uncovered a bug that I'd have missed!  I'm content the missing character is a bug/anomaly in LCDd - we're definitely sending the right text strings to the display as your tcpdump showed!

**Comment by phl0** [comment]
In case anyone is interested in the dump:

bildschirmfoto vom 2016-10-29 23-49-00

**Comment by g0wfv** [comment]
The direct download link has no file at the end of it @phl0 - perhaps the user delated the file - did you download the other file linked in that thread?

https://dl.dropboxusercontent.com/u/9545165/hd44780.so 

BTW, this effects newer RPi 2 & 3 where the processor is a BCM2709 instead of the BCM2708 in the older RPi 1 - someone mended the driver to incorporate the changes to the boards revisions.

**Comment by phl0** [comment]
Yupp. Edited and corrected my post above.

**Comment by iball** [comment]
Works like a charm.  I dusted off an old Sparkfun serLCD 16x2 I had, threw it on an FTDI serial-toUSB and plugged it into my 7" weathernet Pi display (shows weather and network/firewall stats) and have a DVMega on the far side of the room using internal wifi on another Pi for it's network connection.
Works like a champ.
file1 1

**Comment by g0wfv** [comment]
@iball #Like!

**Comment by g0wfv** [comment]
@phl0 I don't suppose you you still have a copy of the modified hd44780.so file kicking about somewhere?  I seem to have lost the downloaded file on my corrupt SD card, and the dropbox download  is now error 404 :-1:

**Comment by phl0** [comment]
There were two links:

https://www.dropbox.com/s/mtkv226gi83ktra/hd44780.so

and 

https://dl.dropboxusercontent.com/u/9545165/hd44780.so

**Comment by phl0** [comment]
Grrrr. Both not working. Will have a look at my MMDVM systems.

**Comment by g0wfv** [comment]
Yes, looks like someone has cleared out their Dropbox - I had a copy of the file up until 3 days ago!  It disappeared with the corrupt SD card (I may still have a copy on my old laptop, but that's at home!)

It should be easy enough to recompile from source if all else fails, and reading some more (and remembering bits!) this only affected you because you were using an RPi 2 or 3 with its newer GPIO addressing; my RPi 1 was unaffected so I may not need the file after all!

That said, I may have *another* broken HD44780 on my hands here as it is refusing to play ball with LCDd and i2c (but it could just as likely be me forgetting something or, even more likely, being stupid!)

I was trying to get it to play nicely on a Pi-Star image, but didn't trust what magic it was doing under the hood so now going back to a home-rolled image since I've got a couple of new SD cards to play with - will update when I figure out what's going on .....

**Comment by g0wfv** [comment]
It was the distrib hd44780.so library module and my PCF8574 adapter having incompatibility issues; it would seem mine are wired in an "alternative" fashion.

I used a precompiled version of hd44780.so from [here](https://github.com/wilberforce/lcdproc) which allows you to specify the wiring schema used in the /etc/LCDd.conf file (the example given in README.md worked first time for me!)

@phl0 If and when you get a chance, can you test this precompiled binary against a RPi 2/3?  I'm not sure if it has the changes for the GPIO addressing?!

**Pull request merged**
