### PR TITLE
jb: this hurts. too much..

### PR DESCRIPTION
**Pull request by stefansaraev**
remove the non-working jb impl. it inserts silence where it should not and breaks audio.

### CODE REVIEW

**Comment by pjao** [comment]
Also tested this version, solved a lots of issues on the audio.

**Comment by g4klx** [comment]
I'd prefer this be tested on a branch before adding it to the main source tree. Also there is a new jitter buffer test branch which may be worth you testing. Your implementation is extremely poor if you have an internet connection with lost packets, it undoes all of the reasons behind sequence numbers etc.

**Comment by stefansaraev** [comment]
new jitter did not work for me, it makes it even worse. 

feel free to pick this and add to a separate brandh if you like so. in the meantime, I would tell our users to at least use Jitter=0

**Comment by shawnchain** [comment]
I don't think so, the master code works fine to me. 
What I'm interested is the root cause of your problem, But I don't think it's in the code.
@stefansaraev

**Comment by stefansaraev** [comment]
does mmdvmhost try to reorder based on received seqid?

**Comment by shawnchain** [comment]
> does mmdvmhost try to reorder based on received seqid?
> @shawnchain

Nope, It will just drop the packet with unexpected seq id. But I think most of the time it will not happen, unless you're using it in a long distance network with poor network connectivity, that's the nature of UDP

**Comment by stefansaraev** [comment]
so it just inserts some silence where it thinks "a packet was lost forever" ?

then it makes sense that we both agree, that current jb implementaton does more bad than good, 
whatever the "root cause of my problem" would be, that's irrelevant

**Comment by shawnchain** [comment]
> so it just inserts some silence where it thinks "a packet was lost forever" ?
> 
> then it makes sense that we both agree, that current jb implementaton does more bad than good,
> whatever the "root cause of my problem" would be, that's irrelevant

No I don't agree with your conclusion. 

If you want packet reassembling, try UDP over TCP but with the cost of increased latency.
Or, try LAN connection if you're using Pi or Amlogic boards with poor WiFi design.

Anyway, in my own opinion, your problem should never be triggered if you have a good network connection.

So, could you please introduce your use scenarios a bitter more?  I'm really interested.

**Comment by stefansaraev** [comment]
ok. more than enough time spent on this ;)

**Pull request closed without merging**
