### PR TITLE
DMR TA & GPS decoding; Nextion Displays refinements

### PR DESCRIPTION
**Pull request by on7lds**
Better looking fonts for the Nextion displays
New parameter for selecting ON7LDS Nextion screen layout, where
-the active ip address of the host is showed on main screen
-Nextion DMR page:
* Talker alias (if available) will be decoded and displayed (in green to know it's the TA)
* Font will get smaller if TA is too long

GPS data will be decoded and logged

### CODE REVIEW

**Comment by g4klx** [comment]
Could you remove DMR Id file change please.

**Comment by on7lds** [comment]
I'm very sorry.
I tried
_git checkout -- DMRIds.dat_
_git push_
but nothing seems to be changed.
What is the correct way to do it ? (I'm no github guru)

**Comment by phl0** [comment]
Maybe checking out master from G4KLX, then copy DMRIds.dat to a temporary file. Then checkout devel and mv the temporary file to DMRIds.dat and commit that to your devel branch.

**Comment by phl0** [comment]
Looks good (concerning the DMRIDs.dat)

**Comment by on7lds** [comment]
:-)
And should I do a new PR now ?

**Comment by phl0** [comment]
Nope. As long as it is not merged all commits are automatically added to the PR. No need to make a new PR. Just leave this one open for @g4klx to merge.

**Comment by on7lds** [comment]
Thanks.
Now I need  a cup of coffee and something sweet with it.

**Pull request merged**
