### PR TITLE
Implement periodic read of DMRIDs.dat using pthread on Linux only.  Also small addition to TGRewrite. 

### PR DESCRIPTION
**Pull request by hacknix**
As title really. I have been careful to double-check my work and I've shared it with the mailing list in advance and received comments, so hopefully everything is in line with what is expected. 

In this update, I've also made one (small) change to the TGRewrite code. 

As before, tested and working on GB7FR. 

73

Simon

### CODE REVIEW

**Comment by g4klx** [comment]
I've added a cross platform Mutex class. Could you incorporate that instead of using pthreads explicitly?

**Comment by hacknix** [comment]
Yes, of course. I'll certainly give it a try....

**Comment by g4klx** [comment]
Hi Simon. I've been thinking about this. It'd probably be better for me to implement the DMR Id re-reading code. So I'll shut this pull request, but I would like it if you could put up a new pull request with the changes to the TGRewrite code which I can then OK, which should be separate from the DMR Id pull request anyway.

**Comment by hacknix** [comment]
Hi Jonathan,

Sure, no problem. If nothing else, I learnt how to make pthreads and mutexes work, which was new for me!

I will do as you ask.

Simon

On 7 October 2016 09:23:29 BST, Jonathan Naylor <notifications@github.com> wrote:
>Hi Simon. I've been thinking about this. It'd probably be better for me
>to implement the DMR Id re-reading code. So I'll shut this pull
>request, but I would like it if you could put up a new pull request
>with the changes to the TGRewrite code which I can then OK, which
>should be separate from the DMR Id pull request anyway.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/g4klx/MMDVMHost/pull/172#issuecomment-252181299

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request closed without merging**
