### PR TITLE
Update DMRIds.dat

### PR DESCRIPTION
**Pull request by vk4tux**
WW  2016-05-14 04:15	vk4tux

### CODE REVIEW

**Comment by g0wfv** [comment]
Hahaha same idea, Adrian!  Just trying to call you on both 4400 and 4805.  I'll close my PR.

**Comment by vk4tux** [comment]
Tony, i think your list was longer than mine, so I closed mine if you 
can redo #68 please.

**Comment by g0wfv** [comment]
Yeah will do :)

On Sat, May 14, 2016 at 4:26 PM vk4tux <notifications@github.com> wrote:

> Tony, i think your list was longer than mine, so I closed mine if you
> can redo #68 please.
>
> On 15/05/16 00:52, Tony Corbett wrote:
> >
> > Hahaha same idea, Adrian! Just trying to call you on both 4400 and
> > 4805. I'll close my PR.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/g4klx/MMDVMHost/pull/69#issuecomment-219224476>
> >
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/g4klx/MMDVMHost/pull/69#issuecomment-219226255>
>
-- 

A J Corbett

G0WFV

**Comment by g0wfv** [comment]
Done

On Sat, May 14, 2016 at 4:38 PM Tony Corbett <tonyc.uk@gmail.com> wrote:

> Yeah will do :)
>
> On Sat, May 14, 2016 at 4:26 PM vk4tux <notifications@github.com> wrote:
>
>> Tony, i think your list was longer than mine, so I closed mine if you
>> can redo #68 please.
>>
>> On 15/05/16 00:52, Tony Corbett wrote:
>> >
>> > Hahaha same idea, Adrian! Just trying to call you on both 4400 and
>> > 4805. I'll close my PR.
>> >
>> > —
>> > You are receiving this because you authored the thread.
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/g4klx/MMDVMHost/pull/69#issuecomment-219224476>
>> >
>>
>> —
>> You are receiving this because you commented.
>>
>>
>> Reply to this email directly or view it on GitHub
>> <https://github.com/g4klx/MMDVMHost/pull/69#issuecomment-219226255>
>>
> --
>
> A J Corbett
>
> G0WFV
>
-- 

A J Corbett

G0WFV

**Comment by vk4tux** [comment]
http://2.imimg.com/data2/NM/EF/MY-3697586/vhf-uhf-bi-directional-repeater-interface.pdf


anyone using GM338's on the mmdvm successfully ?

**Pull request closed without merging**
