### PR TITLE
Added download of YSFHosts.txt to dowload script

### PR DESCRIPTION
**Pull request by kc2vrj**

### CODE REVIEW

**Comment by g4klx** [comment]
Sorry to be a pain, but could you put it into a separate script file instead? I think that would be better.

**Comment by g4klx** [comment]
A further thought. This belongs in the YSF Gateway directory of the YSF Clients project, not in the MMDVM Host as the host does not use that file.

**Comment by kc2vrj** [comment]
Ok no problem

**Comment by kc2vrj** [comment]
ok request moved

**Pull request closed without merging**
