### PR TITLE
Fixed bug in TG Rewrite. Tidy up in DMRAccessControl.cpp, DMRAccessControl.h and MMDVM.ini

### PR DESCRIPTION
**Pull request by hacknix**

### CODE REVIEW

**Comment by g4klx** [comment]
Please remove the .kateproject file, it isn't relevant to the MMDVM.

**Comment by hacknix** [comment]
Removed file as requested. - Sorry, that file was there just to allow loading of the project into Kate on Linux, but I will keep it locally.

**Comment by ea8cwb** [comment]
Not understand. You tell me then that although not this in anyway ini re address continues to make it about the tg9 if from the make the call to a group?
I currently have not experienced any problem even if it is true that I have not updated the version of the Mmdvmhost. I have to try it...

**Comment by ea8cwb** [comment]
Hi. Please, I have updated to the new version of MMDVMHost and the TGRewrite options are not implemented:

TGRewriteSlot1=1
TGRewriteSlot2=1
BMAutoRewrite=1
BMRewriteReflectorVoicePrompts=1
DirectDial=0
TargetTG=9

They are not implemented as you told me, and I do not understand why they have been removed.

There are many of us who are operating using these parameters.

"I request that they be restored again, please." For me and many local folks here in Spain.

Thank you very much, I await your news.

**Pull request merged**
