### PR TITLE
Get DG-ID clean for YSFGateway use

### PR DESCRIPTION
**Pull request by msraya**
New software YCS needs that DG-ID not be clear to zero.
But only I want to merge DG-ID commit: a988d9ec3e21226ae3dbf0ece900902d27a98dbe

### CODE REVIEW

**Comment by g4klx** [comment]
Could you delete your commented out lines. We can use Git to get them back if we need to. Also I'm not happy about your changes to the README file, if/when we merge into master we'll lose the existing and important README information.

**Comment by msraya** [comment]
Ok, I don't mind the README.md. I do not know how to pull request on only one commit, the a988d9ec3e21226ae3dbf0ece900902d27a98dbe . If you can change it for me, I appreciate. 

The changes in code can interfere with the DG-ID setting option in configuration file, so i think you can add an more option in config or remove the actual option about static DG-ID. I don't know if anyone is using this static DG-ID configuration.

The changes in the readme file is only to share and differentiate the main goal of changes from the initial goal of program. Sorry, I don't understand fully the github working philosophy yet, but I'm studying.

Manuel

**Comment by g4klx** [comment]
Another problem is that your changes go onto the master branch, it would be better to apply them to a separate branch to be tested before being added to master. I've created a new branch DGID based on master which you can use. Could you close this pull request, make the changes against the DGID branch and do a pull request on that one?

**Comment by shawnchain** [comment]
@msraya  That is really amazing work you have did,  and I would love to see the changes get merged into the trunk!

To work with git-flow, I would like to suggest you:

- Fork from G4KLX's repository (that's done)
- Create a working branch like "ysf-something-going-to-happen"
- Submit your changes to the working branch for One Single Feature
- Test for several days with your hotspot or repeater
- Create a pull request to G4KLX's upstream repository and wait for the merge
- Repeat for the next feature

Cheers,
BG5HHP

**Comment by g4klx** [comment]
The DG-ID code was re-purposed DSQ code which did something else, Not knowing too much about DG-ID I assumed it could be used in the same way, obviously not. At some stage we should maybe look into using DG-ID instead of, or as well as, Wires-X to select FCS and YSF reflectors? This would need to be done in YSF Gateway of course. I think Yaesu want to phase out Wires-X but I may be wrong.

**Comment by msraya** [comment]
"@msraya That is really amazing work you have did, and I would love to see the changes get merged into the trunk!"

Thank You!! I need to improve my github skills and my english language skills also.

"it would be better to apply them to a separate branch to be tested before being added to master. I've created a new branch DGID based on master which you can use. Could you close this pull request, make the changes against the DGID branch and do a pull request on that one?"

Of course I will do. Only I try to do it as soon as possible. 

"The DG-ID code was re-purposed DSQ code which did something else, Not knowing too much about DG-ID I assumed it could be used in the same way, obviously not. At some stage we should maybe look into using DG-ID instead of, or as well as, Wires-X to select FCS and YSF reflectors? This would need to be done in YSF Gateway of course. I think Yaesu want to phase out Wires-X but I may be wrong."

I think DG-ID in old times was used to grant access to node, that's the original MMDVMHost purpose. Some similar to DIGITAL CODE SQUELCH. 

But some guys are working now in the new IMRS interconnection scheme (Wires-II) to be used outside Yaesu own network and control. They use the DG-ID feature to change virtual reflectors (only 99) so they can be compatible with the IMRS idea. The implementation right now is poor, callsign and gps information is lacking, but it is working and I hope they improve in new versions.

Some people, want to try the new interconnection scheme based on DG-ID numbering. It's so simple, only we need to keep the DG-ID information without changing. So I think It can be solved by simply not reset to zero by default.

I'm going to close this request and propose an new one on DGID branch. 
I'll keep this thread open for two days.
Regards
Manuel

**Comment by iz5wga** [comment]
I'm not a developer, just a Linux admin and ham radio operator. Is there anything, even tests, I could do to help you implement this? YCS and Europelink reflector are growing and we do need the DG ID support.
Thanks!

**Pull request closed without merging**
