### PR TITLE
Detect D-Star DV Fast Data on a per-frame basis

### PR DESCRIPTION
**Pull request by timclassic**
This is my attempt at fixing the remaining D-Star DV Fast Data corruption observed in https://github.com/g4klx/MMDVMHost/issues/470#issuecomment-459227905.  I removed the existing detection logic by reverting previous commits (and adding back a few changes that looked important and unrelated to fast data support).  Then I reimplemented FEC recalculation avoidance and DTMF blanking avoidance on a per-frame basis.

Specifically, the presence of Fast Data is discovered by reading the mini-header in every second data frame.  If found, FEC regeneration and DTMF blanking are disabled for the current and next voice frames.  An exception is voice frames that have a sync frame instead of a data frame.  Commit 8874d12 punts on this particular issue by just disabling FEC and DTMF blanking for those frames altogether.  The next commit, efe9b3d, adds code to handle this issue by delaying FEC and DTMF processing of these voice frames until the first data frame can be read.  This appears to work well in practice.  The diagrams in https://github.com/timclassic/d-star/blob/master/std5_0b.en.pdf show the frame and block layouts.

An interesting detail is that DTMF blanking destroys the periodic beeps that are inserted during fast data transmissions, which are essentially regular voice blocks in the middle of the fast data block stream.  Rather than disable DTMF blanking until the end of the transmission, I implemented a grace period that delays DTMF blanking for the first six frames after switching back to voice mode.  This enables the transmission tones to survive but will quickly reenable blanking for actual voice traffic.

I also added detection of null AMBE data in b2844bc, which is often (always?) sent by the Kenwood TH-D74 in the first 21 voice frames, and I've also seen it at the end of a transmission.  FEC recalculation and DTMF blanking is also avoided for these frames, as there is no DTMF by definition and the FEC recalcuation always reports errors.

The final commit, bf5651b, removes all the debugging statements I added.  Running the code before this commit might help in validating the implementation.

I tested this code by transferring images among the following radios via REF072D using Fast Data:

- Icom IC-9700
- Icom IC-705
- Kenwood TH-D74A

I also performed a number of tests with various files, and D-Rats also appears to work better than before.

I used MMDVMHost with these patches on both a ZUMSpot and a Raspberry Pi with a ZUM Radio MMDVM-Pi rev 1.0 board.

I also verified that the corruption observed in https://github.com/g4klx/MMDVMHost/issues/470#issuecomment-459227905 (in dstar-received.log) is no longer present.

### CODE REVIEW

**Comment by shawnchain** [comment]
would like to know if the change would effect the normal d-star voice packet repeating?

**Comment by g4klx** [comment]
I hope not.
    On Wednesday, 16 December 2020, 16:37:28 GMT, Shawn <notifications@github.com> wrote:  
 
 


would like to know if the change would effect the normal d-star voice packet repeating?

**Comment by narspt** [comment]
Hi Guys, I'm sorry to tell but some change included on this PR seems causing an annoying problem on normal D-Star voice repeating, apparently it is only triggered by some specific transmissions (I'm unsure if radio specific, gps info, or if when there are errors, no idea... it doesn't happen when listening all stations, just on specific ones apparently), it makes radios beep (like EOT beep) occasionally/randomly while RX'ing the hotspot with updated MMDVMHost with these changes. @MW0MWZ was apparently also able to reproduce this problem before, as well as some other person that reported it to him.

Today I did some testing with a friend and I was able to successfully record the stream of some of his transmissions exhibiting the problem, I was then able to always reproduce the issue easily when replaying these recorded streams, this allowed me to do more tests and conclude that it is really caused by changes on this PR.
(i.e. if I checkout 787393e4c275d54e9f4d62cc74fb365d0faece66 - this is just before merging the PR - and compile it then I have NOT the problem, but if I checkout 4897313fc05afb5f74974bb5b36c4aeed017f4e9 - this is just when the PR is merged - and compile it then I have the problem)

You can test it with my stream recordings on this file: [pr667-problem.zip](https://github.com/g4klx/MMDVMHost/files/6652176/pr667-problem.zip)
just test by replaying them using voicetransmitd and you should be able to reproduce the problem, each file is a different transmission and at some point the problem is triggered once on each of the 3 files (sometimes it is much more frequent, but this is what I was able to catch while recording, just one on each).

If it matters: my friend was using an Icom ID-51E, MMDVM_HS hotspot, connected to a XLX reflector, I was listenning him using an ID-31E and DVMega hotspot, and... at same time recording streams from reflector using pydv tools.

**Comment by narspt** [comment]
Just to add, I did some more testing concerning this problem with beeps during transmissions and found that all is ok (no beeps) with commit 8656aaedaa17f99838f7922e029876494a85d096 as well as with 8874d1262b1b6815954f08a04212b4a1a14ffd54, but I can reproduce the problem since commit efe9b3d45956873da57e6a43832ddcf4edb26f74 

Also note that @MW0MWZ found another issue https://github.com/g4klx/MMDVMHost/issues/702 with DTMF tones no longer working at all to control ircDDBGateway, apparently associated to the same commit.

**Comment by timclassic** [comment]
@narspt Thanks for the recording and for the finding the problematic git commit!  My immediate suspicion after thinking about this for ~one minute is the small delay introduced for voice frames followed by a sync frames by efe9b3d.  Maybe all other frames could be delayed by a similar amount of time to keep the stream flowing consistently?

Unfortunately I won’t have time to debug this further until about two weeks from now.  I’ll try to pay attention here in the meantime in case anyone else decides to take a look.

Another option would be to revert just efe9b3d until a better version can be written.  The downside there is that we will no longer do DTMF blanking or FEC recalculation on Voice frames that are followed by a Sync frame, e.g. every 21st voice frame (if memory serves).  Perhaps @g4klx has an opinion.

**Comment by timclassic** [comment]
Random idea that might not even apply here: Is there a jitter buffer that manages the TX data flow from MMDMVHost to the MMDVM for transmission?  If so, perhaps increasing this buffer length by 20ms would resolve the issue.

**Comment by g4klx** [comment]
The jitter buffer idea won't work. The problem is something fundamentally wrong with the fast data handling, and it needs sorting ASAP.

**Comment by timclassic** [comment]
If this needs to be resolved immediately, I think the options are:

1. Revert the changes in this PR, restoring the old state
2. Assuming someone can test: Revert only efe9b3d, test to see if the dropouts and DTMF issues are resolved, and live for a little while without DTMF blanking and FEC recalculation on every 21st voice frame

I prefer option 1 since it feels like a better state to be in.  Later I can test with the sample provided by @narspt and submit a new PR once the issue is resolved.

Unfortunately I'm not in a position to work on this, as I'm away from my equipment for a few weeks.

**Comment by timclassic** [comment]
> If it matters: my friend was using an Icom ID-51E, MMDVM_HS hotspot, connected to a XLX reflector, I was listenning him (live and then the recordings) using an ID-31E and DVMega hotspot, and... at same time recording streams from reflector using pydv tools.

@narspt, Which of the two hotspots were running with commit efe9b3d when the recordings were made?

Were you using dv-recorder to connect directly to the XLX reflector, leaving your own hotspot out of the loop when making the recordings?

**Comment by narspt** [comment]
@timclassic: My friend's hotspot had older MMDVMHost without any of the changes on this PR (actually it is the version that was included on Pi-Star since "Jun 15, 2020", before Andy finally update it on last few days) and I was listening him using fully updated MMDVMHost, surely including all the changes on this PR. My friend couldn't apparently notice problems on my TX.

Yes, I used the recorder tool directly connected to the XLX. My hotspot was also connected to the XLX, but two independent connections direct to reflector (recorder using DExtra and hotpot using DCS). I was listening my friend live and recording at same time, and I can tell that when I heard the beeps live then I just asked him to wait, replayed the recorded stream using voicetransmitd and the beep sounds exactly at same point in his transmission that I heard it live, and it's always there every time I replay it, unless I replay it using MMDVMHost without the problematic commit.

**Comment by MW0MWZ** [comment]
I've been working on the DTMF problem today - and now I understand it at least.

DStarControl.cpp - there is an IF that starts on line 488; this IF does a few things, including sending the data stream to RF and/or to Network.
The problem is that the new function "maybeFixupVoiceFrame" only fires once (because this IF is only hit once for both network and RF) and assumes that if "m_duplex" is true, then it should blank the DTMF frames, the problem is that when that happens, those frames are blanked for RF and network because they only go through this IF one time and handle both RF and Network at the same time. This is why DTMF frames were blanked specifically and only at the m_duplex section.
 @timclassic are you able to fix that up please?

**Comment by timclassic** [comment]
@MW0MWZ Unfortunately I'm not in a position to work on this right now, as I'm away from my equipment for a few weeks with no way to make and test changes.

Thank you, though, for debugging!  This will be very helpful when I can start fixing the code.

**Comment by MW0MWZ** [comment]
I'm aware that you are not near your equipment, but you might be able to look at the code and see the issue; For example, here is one way to fix it: https://github.com/MW0MWZ/MMDVMHost/commit/c1121a37add30a234b925f4ef702186a1e55b563 this may or may not be the appropriate answer, but its one way - essentially moving the DTMF blanking out of the function and back to the code.

Since you only do DTMF Blanking when the data isn't D-Star fast data (so there will be no DTMF of course) this may have a negative impact on fast data - @timclassic I would appreciate your thoughts on this...

**Comment by timclassic** [comment]
@MW0MWZ I'll do my best to read over this ASAP.

**Comment by F4FXL** [comment]
Hi folks,

Just came accoss this  after navigating through various issues. My journey through theses issues started here: https://github.com/F4FXL/DStarGateway/issues/48

By reading all the discussion some issues I had on our club repeater for 4 years now. We had exactly the symptoms described here: apparent end of frames from stations coming through repeaters with newer had periodically EOT in the middle of their transmissions.
I put the blame on the internet provider, even changed all of the 4G hardware, and then I read this ! :D

So what is the status @timclassic , as it been fixed or not@

**Pull request merged**
