### PR TITLE
Nextion RSSI & BER display workaround / Fix Linux compilation warnings

### PR DESCRIPTION
**Pull request by g0wfv**
Impliments IW9GRL's RSSI & BER display workaround for all modes (supercedes PR #385)

Fixes Nextion.cpp compilation warnings on Ubuntu 17.10

Fixes LCDproc.cpp display bug with P25 RSSI display

### CODE REVIEW

**Comment by g0wfv** [comment]
As commented on Yahoo ....

> Daniele,
> 
> Hmmmmm?  Odd one this.  The changes I made do not (should not) impact on that function and I'm not getting that particular compilation error, just compile time warnings about the size of the character buffer (which I've fixed in my version - PR to follow)
> 
> I am however compiling on Ubuntu; I will try to compile for Raspbian and see if there is any difference.
> 
> It may be that my patch imported into your code has made some kind of funny.  If mine compiles fine, I'll submit a PR directly to Jon's upstream repo from my fork.
> 
> Tony
> 
> Update (I should have waited before hitting send on my last email .....)
> 
> Mine compiles fine on both Ubuntu and Raspbian; I'll submit a PR direct to Jon.
> 

````
pi@raspberrypi:~/MMDVMHost $ make clean all
rm -f MMDVMHost *.o *.d *.bak *~ GitVersion.h
echo "const char *gitversion = \"ed4c3b96c109b28545a3817e9b14d6b8f968dafc\";" > GitVersion.h
g++ -g -O3 -Wall -std=c++0x -pthread -c -o AMBEFEC.o AMBEFEC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o BCH.o BCH.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o BPTC19696.o BPTC19696.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o Conf.o Conf.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o CRC.o CRC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o Display.o Display.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMRControl.o DMRControl.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMRCSBK.o DMRCSBK.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMRData.o DMRData.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMRDataHeader.o DMRDataHeader.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMREMB.o DMREMB.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMREmbeddedData.o DMREmbeddedData.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMRFullLC.o DMRFullLC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMRLookup.o DMRLookup.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMRLC.o DMRLC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMRNetwork.o DMRNetwork.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMRShortLC.o DMRShortLC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMRSlot.o DMRSlot.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMRSlotType.o DMRSlotType.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMRAccessControl.o DMRAccessControl.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMRTrellis.o DMRTrellis.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DStarControl.o DStarControl.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DStarHeader.o DStarHeader.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DStarNetwork.o DStarNetwork.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DStarSlowData.o DStarSlowData.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o Golay2087.o Golay2087.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o Golay24128.o Golay24128.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o Hamming.o Hamming.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o JitterBuffer.o JitterBuffer.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o LCDproc.o LCDproc.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o Log.o Log.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o MMDVMHost.o MMDVMHost.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o Modem.o Modem.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o ModemSerialPort.o ModemSerialPort.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o Mutex.o Mutex.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o NetworkInfo.o NetworkInfo.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o Nextion.o Nextion.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o NullDisplay.o NullDisplay.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o P25Audio.o P25Audio.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o P25Control.o P25Control.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o P25NID.o P25NID.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o P25Trellis.o P25Trellis.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o P25Utils.o P25Utils.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o QR1676.o QR1676.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o RS129.o RS129.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o RS241213.o RS241213.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o RSSIInterpolator.o RSSIInterpolator.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o SerialController.o SerialController.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o SerialPort.o SerialPort.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o SHA256.o SHA256.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o StopWatch.o StopWatch.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o Sync.o Sync.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o TFTSerial.o TFTSerial.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o Thread.o Thread.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o Timer.o Timer.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o UDPSocket.o UDPSocket.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o UMP.o UMP.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o Utils.o Utils.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o YSFControl.o YSFControl.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o YSFConvolution.o YSFConvolution.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o YSFFICH.o YSFFICH.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o YSFNetwork.o YSFNetwork.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o YSFPayload.o YSFPayload.cpp
g++ AMBEFEC.o BCH.o BPTC19696.o Conf.o CRC.o Display.o DMRControl.o DMRCSBK.o DMRData.o DMRDataHeader.o DMREMB.o DMREmbeddedData.o DMRFullLC.o DMRLookup.o DMRLC.o DMRNetwork.o DMRShortLC.o DMRSlot.o DMRSlotType.o DMRAccessControl.o DMRTrellis.o DStarControl.o DStarHeader.o DStarNetwork.o DStarSlowData.o Golay2087.o Golay24128.o Hamming.o JitterBuffer.o LCDproc.o Log.o MMDVMHost.o Modem.o ModemSerialPort.o Mutex.o NetworkInfo.o Nextion.o NullDisplay.o P25Audio.o P25Control.o P25Data.o P25LowSpeedData.o P25Network.o P25NID.o P25Trellis.o P25Utils.o QR1676.o RS129.o RS241213.o RSSIInterpolator.o SerialController.o SerialPort.o SHA256.o StopWatch.o Sync.o TFTSerial.o Thread.o Timer.o UDPSocket.o UMP.o Utils.o YSFControl.o YSFConvolution.o YSFFICH.o YSFNetwork.o YSFPayload.o -g -O3 -Wall -std=c++0x -pthread -lpthread -o MMDVMHost
````

**Comment by g4klx** [comment]
This has been applied manually because of other changes, also you included your MMDVM.ini file!

**Comment by g0wfv** [comment]
#Rusty #NotPayingAttention #Woops

**Comment by iw9grl** [comment]
Thank you guys.... I'll try soon.... 73

**Pull request closed without merging**
