### PR TITLE
Change ovcm config to int value

### PR DESCRIPTION
**Pull request by shawnchain**
Change OVCM config item to int value to save class constructor params and member variables.

### CODE REVIEW

**Comment by g4klx** [comment]
Would not an enumeration be a better choice?


Sent from Yahoo Mail for iPhone


On Saturday, November 16, 2019, 15:12, Shawn <notifications@github.com> wrote:


Change OVCM config item to int value to save class constructor params and member variables.

You can view, comment on, or merge this pull request online at:

  https://github.com/g4klx/MMDVMHost/pull/534

Commit Summary
   
   - Change ovcm config to int value

File Changes
   
   -  M Conf.cpp (14) 
   -  M Conf.h (6) 
   -  M DMRControl.cpp (4) 
   -  M DMRControl.h (2) 
   -  M DMRSlot.cpp (20) 
   -  M DMRSlot.h (5) 
   -  M MMDVM.ini (2) 
   -  M MMDVMHost.cpp (13) 

Patch Links:
   
   - https://github.com/g4klx/MMDVMHost/pull/534.patch
   - https://github.com/g4klx/MMDVMHost/pull/534.diff

**Comment by g4klx** [comment]
Does this work?

For example, you use:

csbk.setOVCM(m_ovcm & DMR_OVCM_TX_ON);

Should that not be:

csbk.setOVCM(m_ovcm == DMR_OVCM_TX_ON);

Since the argument to setOVCM is a bool and a == is logically a bool also. I'd much rather see an explicit test.

Otherwise it looks good.

**Comment by g4klx** [comment]
If you are testing for two or more values in the enum in one go then please use == and || for a proper logical construction.

**Comment by shawnchain** [comment]
> If you are testing for two or more values in the enum in one go then please use == and || for a proper logical construction.

Fixed, thanks for your comments.

**Pull request merged**
