### PR TITLE
Add RSSI to (4-line) HD44780 and LCDproc displays

### PR DESCRIPTION
**Pull request by g0wfv**
RSSI added to LCDproc displays - compiles but needs testing

RSSI code bones added to 4-line HD44780 LCDs in the hope someone who can test and fettle the code without doing it blind can do so .... compiles but needs testing

Also removed all old scrolling code as it aint getting put back in!  If you want scrolling, may I suggest the LCDproc support instead?!

### CODE REVIEW

**Comment by iw9grl** [comment]
Great, I'm waiting for merge!!!  Thank you Tony

**Comment by g0wfv** [comment]
As the PR says, the bones are there, but it needs testing (which is where you come in, Daniele!) and will probably need some fettling (slight alteration) for positioning and logic - I'm hoping someone who is able to test changes can do this as I only run a DVMega (for now!) and do not have the capability to generate RSSI output.   I could, of course, have gotten this completely wrong and although it runs on my DVMega based setup, completely fails on an MMDVM (but I'm hoping not!)

@phl0 Any chance you can dig out a HD44780 to assist with the testing and adjustment?  @iw9grl is going to do some initial testing as he runs a HD44780 full-time, but won't be able to do the coding bit ....  might speed things up?

**Comment by iw9grl** [comment]
Tony, I hope to test all tomorrow morning, I will try to do some code fixes if necessary, I'm sorry but I'm not good skilled to modify these codes, but I can try !!!
for now many many thank you for this appreciated contribute !
73 de IW9GRL

**Comment by phl0** [comment]
I will dig out my HD44780 tomorrow and test your code :)

**Pull request merged**
