### PR TITLE
add IPv6 support

### PR DESCRIPTION
**Pull request by jg1uaa**
DMR is tested with XLX (XLX765) and BrandMeister Master (3101, 2841)
POCSAG is tested with IPv6 capable DAPNETGateway.
Others are not tested, maybe work.

Due to lack of providing address string, RemoteControl.cpp cannot support IPv6.
LCDProc.cpp is not yet.

details at https://github.com/g4klx/MMDVMHost/issues/563

### CODE REVIEW

**Comment by stefansaraev** [comment]
works fot me. thanks much!

I guess you should remove reverted commits (and their reverts) and maybe squash/cleanup commit history a bit.

**Comment by stefansaraev** [comment]
works for me, thanks!

Iguess you should remove reverted commits (and their reverts) and squash/clean up commit history a bit.

**Comment by jg1uaa** [comment]
@stefansaraev thank you for testing, and I fixuped commit history with your advise.

**Comment by jg1uaa** [comment]
I think about following problem.

> Due to lack of providing address string, RemoteControl.cpp cannot support IPv6.

How about adding Address parameter in [Remote Control] section?
It can choose not only IPv4/IPv6, but also using network interface. 

Current remote control feature uses 0.0.0.0 (INADDR_ANY), this means MMDVMHost accepts remote command from **all** network interfaces... maybe it will cause security issue.

I think specifying Address=127.0.0.1 as default is not bad idea, but is there any reason that accepting commands from multiple interfaces?

**Comment by g4klx** [comment]
I think you're right about only allowing for the remote commands to be from the localhost, but adding an address parameter (with a default of 127.0.0.1 of none given) is a very reasonable thing to do.

**Comment by jg1uaa** [comment]
Remote control feature is fixed.

maybe almost all required IPv6 stuff has implemented.
DMR and POCSAG works no problem, but other digital modes are not tested because I don't have systems.

**Pull request merged**
