### PR TITLE
Adding Flags to the Nextion Display - GB7FH

### PR DESCRIPTION
**Pull request by GB7FH**

### CODE REVIEW

**Comment by GB7FH** [comment]
Update

**Comment by g4klx** [comment]
Two things: firstly, the code has conflicts according to git. Please ensure that there are no conflicts. Secondly, can you configure the prefix to number via a config file that is read in and then used to populate something like a std::unordered_map for lookup. This would be more efficient and dynamic to allow for changes without a recompile.

**Comment by g0wfv** [comment]
Addressing Jon's points in order ...

**1st  point ...**

The issue with the conflicts is you haven't merged other commits that have taken place whilst you have been developing your code.

For example, the base for your code is commit dad34a which is now 11 commits behind Jon's master repository ...

> This branch is 1 commit ahead, 11 commits behind g4klx:master.

If Jon was to merge your commit, I would expect there to be the potential to lose the various fixes and additions to the code since commit dad34a (and we've had enough complaints about the CWID not working for it to be broken again!)

**2nd point ...**

All those if / elseif statements would require a change to the code each time a DXCC entity changes or a new one is added.  An easily maintainable file based on an already available DXCC entity list that could be read in at program start would be the way to go with this one.  Yes it will require some maintenance, but not as potentially destructive as editing the source code and recompiling each time (potential to introduce bugs etc!)

That said the ARRL wants about $6 to get your hands on the latest list and it's for personal use only!  There are other lists out there, but how accurate (up-to-date) are they?

**Comment by GB7FH** [comment]
Thank you, still learning how GIT works, last night when I did the pull it stated I was 1 commit ahead but today from the git web site it said 9 behind an when I pressed it 11 behind so I still have to get my head around that.

Happy to put the data in an adaptation file, I admit I had resorted to type as it was frowned upon in my previous software role. As for the actual data I had sourced it from many websites and I do not think I have broken any copyrights in doing so. I will check them again for any disclaimers.

I will try again as I am enjoying this.... David

**Pull request closed without merging**
